# Generated by Django 5.0.7 on 2024-07-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binderapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
