# Generated by Django 5.0.7 on 2024-07-14 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binderapi', '0002_alter_snippet_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='binderapi.directory'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='binderapi.directory'),
        ),
    ]
